---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define chrony_packages.
  set_fact:
    chrony_packages: "{{ __chrony_packages | list }}"
  when: chrony_packages is not defined

# Setup/install tasks.
- include: "setup-{{ ansible_os_family }}.yml"

- name: update chrony.conf from template
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: chrony_conf

- name: ensure chrony service is started and enabled
  service:
    name: "{{ chrony_service_info.name }}"
    enabled: yes
    state: started
    pattern: chronyd

- name: ensure chrony service is restarted if necessary
  service:
    name: "{{ chrony_service_info.name }}"
    state: restarted
    pattern: chronyd
  when: chrony_conf|changed
